* Tests performed: Frequency and amplitude based onset detection algorithm

**   Frequency based

*** High threshold (0.6) & gain sound card (1/4) =======>
    1 table hit is not detected. One has to hit the table quite hard for it to be detected.

    2 very low signals are still detected despite the high threshold.

    3 scratching is detected as multiple impacts but a lower threshold is needed for them to be detected for sure.

    4 loud claps are detected

*** Low threshold: (0.1) & gain sound card(1/4) ========>
    1 table hits are detected. Even the small ones.

    2 reacts good to the scratching.

    3 loud claps are detected more than before.



** Time based

*** High threshold (0.00044) & gain sound card (1/4) =======>
    1 better performance than fft, table hit is not detected. One has to hit the table quite hard for it to be detected.

    2 performance for very low signals is not very good, some signals with fast transient are detected very nicely (exp. mallet stick (upwards)) others are not.

    3 performance for scratching is not good at all, most of the scratching is not detected. One has to scratch very intensivly for it to respond

***  Low threshold: (7.19401e-06) & gain sound card(1/4) ========>
    1 very low signals are not detected (pp pianissimo and more quiet => (ppp)).

    2 better performance compared to FFT reqarding other sounds such as table impact, although loud claps are detected. Still beter than FFT regarding claps.

    3 scratching is detected as multiple impacts, good performance.
