#+TITLE: Algorithm documentation

* General
This documentation will describe the implemented algorithm for the plausibility experiment entitled: "Schrodinger's box".  The operation will be described in a chronological order starting from the initial input signal to the final output of the sample playback.

The entire algorithm is written in SuperCollider and it is applied/compiled on the Bela platform.  The following prerequisite is required:
- ddwVoicer(https://github.com/jamshark70/ddwVoicer)

We will divide the system into three parts for greater ease of analysis.
+ Onset detection algorithms, time based algorithm (TBA) & frequency based algorithm (FBA).
+ Sample player
+ Onset detection logic

In addition, (a SuperCollider patch for) an interface was also implemented.  In that way the user will be able to configure certain parameters of the system.  In particular, the threshold of the TBA & FBA onset detection algorithms and an option for different sample playback sounds.

* Onset detection

The onset detection algorithms (ODA) are the first elements in the signal processing chain applied to the input signal.  As already stated, there are two types of onset detection.  The most instant/fast but less reliable is the time based algorithm (TBA).  The frequency based algorithm (FBA) is less fast but significantly reliable compared to the TBA.  In the first stage the 4 channels are mixed to a single one.  Then, split and used as input for both ODA.

** TBA

For the TBA algorithm we were based on certain elements of the practice suggested by Turchet [1].
Primarily, the input signal is filtered using a high pass filter at 4kHz before onset detection.  In this way a large number of false detections will be limited.  (calculate energy, cite Turchet) In order to provide reliable detection squaring of the signal was required as suggested by Turchet.  *Thus, a positive waveform will be detected in a more fast and effective way by the threshold detection* [CORRECT].  At this point, the envelope of the signal was calculated by means of the "envelope follower" and after, the derived envelope was smoothed by a fast and a slow low-pass filter.  At first, the fast smoothing takes place by the fast low-pass filter and the derivative (slope) is calculated in the output.  Then, the derivative will be the input for the slow low-pass filter.  The cutoff frequencies for the fast and slow filter are 25Hz and 100Hz accordingly.  After, the trend subtraction takes place.  In particular, an attenuation is applied to the fast filter and the slow is subtracted from it. a * s1(x) - s2(x).  Therefore, the output is always below the signal smoothed by the slow low pass filter, except on onsets.  Subsequently, before the threshold detection a half wave rectification is implemented.  In this way, we are dealing with negative and positive values.  When a positive value appears, a trigger signal is produced to the output.  For the threshold detection we utilised the Schmitt trigger as a level detector.  The high and low threshold are configured from the interface.  In practice, by setting lower values to the low threshold a greater amount of time is required for the next onset to be detected.

** FBA
The FBA calculates the FFT to a given sized buffer (256 samples).  Afterwards an onset detection function is applied on the spectrum of each window of 256 samples.  Whenever an onset is detected a control trigger signal is produced to the output.



work effectively in combination
**

* References
[1] Turchet, Luca. (2018). Hard real-time onset detection of percussive sounds.

[2]

[3]
